### ISSUE TITLE
[Doc] Make terms more clearly defined

### ISSUE THREAD

**Issue by surinrasu** [SagerNet/serenity#29]
Is the profile in serenity the same thing as the profile in sing-box?

If so, why is there a url for each subscription and not for each profile?
According to the doc, profiles are the ones that should have a url:
> At the same time, the graphical client must provide support for importing remote **profiles** through a specific URL Scheme

Hope this suggestion will not be offensive 🥺 As it seems that you have a rather personal approach to your documentation

**Comment by nekohasekai** [comment]
> a url for each subscription and not for each profile

I believe this is a misunderstanding due to lack of documentation, each URL is for a profile, not a subscription
